# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Post(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, title: str=None, content: str=None):  # noqa: E501
        """Post - a model defined in Swagger

        :param title: The title of this Post.  # noqa: E501
        :type title: str
        :param content: The content of this Post.  # noqa: E501
        :type content: str
        """
        self.swagger_types = {
            'title': str,
            'content': str
        }

        self.attribute_map = {
            'title': 'title',
            'content': 'content'
        }

        self._title = title
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'Post':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Post of this Post.  # noqa: E501
        :rtype: Post
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this Post.


        :return: The title of this Post.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Post.


        :param title: The title of this Post.
        :type title: str
        """

        self._title = title

    @property
    def content(self) -> str:
        """Gets the content of this Post.

        post content  # noqa: E501

        :return: The content of this Post.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this Post.

        post content  # noqa: E501

        :param content: The content of this Post.
        :type content: str
        """

        self._content = content
