# coding: utf-8

"""
    Blog posts

    Posts blog  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.post_api import PostApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPostApi(unittest.TestCase):
    """PostApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.post_api.PostApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_post(self):
        """Test case for create_post

        Add a new post to the blog  # noqa: E501
        """
        pass

    def test_delete_post(self):
        """Test case for delete_post

        Delete post  # noqa: E501
        """
        pass

    def test_edit_post(self):
        """Test case for edit_post

        Edit post  # noqa: E501
        """
        pass

    def test_get_post_by_id(self):
        """Test case for get_post_by_id

        Get post by ID  # noqa: E501
        """
        pass

    def test_get_posts(self):
        """Test case for get_posts

        Get all posts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
