---
swagger: "2.0"
info:
  description: "Posts blog"
  version: "1.0.0"
  title: "Blog posts"
host: "127.0.0.1"
tags:
- name: "post"
  description: "Posts blog"
schemes:
- "https"
- "http"
paths:
  /myPosts:
    get:
      tags:
      - "post"
      summary: "Get all posts"
      description: "Returns all posts"
      operationId: "get_posts"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/FullPost"
      x-swagger-router-controller: "swagger_server.controllers.post_controller"
  /myPosts/{postId}:
    get:
      tags:
      - "post"
      summary: "Get post by ID"
      description: "Returns a single post"
      operationId: "get_post_by_id"
      produces:
      - "application/json"
      parameters:
      - name: "postId"
        in: "path"
        description: "ID of post to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Post"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Post not found"
      x-swagger-router-controller: "swagger_server.controllers.post_controller"
  /create:
    post:
      tags:
      - "post"
      summary: "Add a new post to the blog"
      description: ""
      operationId: "create_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Post object that needs to be added to the blog"
        required: true
        schema:
          $ref: "#/definitions/Post"
      responses:
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.post_controller"
  /myPosts/{postId}/edit:
    post:
      tags:
      - "post"
      summary: "Edit post"
      description: "Edit post"
      operationId: "edit_post"
      produces:
      - "application/json"
      parameters:
      - name: "postId"
        in: "path"
        description: "ID of post to edit"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Post object that needs to be added to the blog"
        required: true
        schema:
          $ref: "#/definitions/Post"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Post"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Post not found"
      x-swagger-router-controller: "swagger_server.controllers.post_controller"
  /myPosts/{postId}/delete:
    post:
      tags:
      - "post"
      summary: "Delete post"
      description: "Delete post"
      operationId: "delete_post"
      produces:
      - "application/json"
      parameters:
      - name: "postId"
        in: "path"
        description: "ID of post to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Post"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Post not found"
      x-swagger-router-controller: "swagger_server.controllers.post_controller"
definitions:
  Post:
    type: "object"
    properties:
      title:
        type: "string"
        example: "test"
      content:
        type: "string"
        example: "test constent"
        description: "post content"
    example:
      title: "test"
      content: "test constent"
  FullPost:
    type: "array"
    items:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        title:
          type: "string"
          example: "test"
        content:
          type: "string"
          example: "test constent"
          description: "post content"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
